config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :users
  resources :links

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = current_user.links
  end

  def new
    @link = Link.new
  end

  def edit
    @link = Link.find(params["id"])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      flash[:notice] = "Successfully Edited Link"
      redirect_to links_path
    else
      flash.now[:error] = "A link must have a name and url"
      render :edit
    end
  end

  def create
    @link = current_user.links.new(link_params)
    if @link.save
      flash[:notice] = "Successfully added Link"
      redirect_to links_path
    else
      flash.now[:error] = "Invalid Link."
      @links = current_user.links
      render :index
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:error] = "Invalid"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FINAL</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to "THE BIG ONE", root_path, class: "brand-logo center", id: "logo" %>
        <ul class="right hide-on-med-and-down">
          <% if current_user %>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
          <% unless current_user %>
            <li><%= link_to "Create Account", new_user_path %></li>
          <% end %>
      </div>
    </nav>

    <% if current_user %>
      <h3 class='center'> Welcome, <%= current_user.username %>! </h3>
    <% end %>

<%= yield %>

</body>

</html>

app/views/links/edit.html.erb
<h4 class="center">Edit Link</h4>
<div class="container">
  <%= form_for @link, url: link_path(@link) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.submit "Update Link", class: "btn" %>
   <% end %>
</div>

app/views/links/index.html.erb
<div class="container">
<h2 class="center">Your Links</h3><br>

<h4 class="center">Add New Link</h4>
    <%= form_for Link.new, url: links_path do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :url %>
      <%= f.text_field :url %>
      <%= f.submit "Add Link", class: "btn" %>
     <% end %>
     <br><br><br><br>

 <h4 class="center">Past Links</h4>
 <div class= "container" id="search-bar">
   <input class='validate' type="text" id="search-text" placeholder="Search Links">
 </div>
 <br>
 
 <table class="centered highlight">
     <thead>
       <tr>
         <th>Title</th>
         <th>Link</th>
         <th>Edit</th>
       </tr>
     </thead>
     <tbody id="link-index">
       <% @links.each do |link| %>
       <tr id="link-<%=link.id%>">
         <th class="center link-title"><%= link.title %></th>
         <th class="center"> <a href="<%=link.url%>">Link</a></th>
         <th class="center"> <a href="<%=edit_link_path(link)%>">Edit</a></th>
       </tr>
       <% end %>
     </tbody>
   </table>

 </div>

app/views/users/new.html.erb
<div class="container">
  <h1> Create Account </h1>

  <%= form_for(User.new) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

</div>

app/views/welcome/index.html.erb
<div class= "container">
  <h2>
    This girl right here is trying to get 30 points so she can pass Turing.  Login or Create Account to help her on this journey.
  </h2>
  <br><br>
   <img class="materialboxed" width="650" src="http://i.imgur.com/vR8iphs.jpg">
</div>